- histogram/Cargo.toml
- histogram/README.md
Prepare the rustcommon histogram crate for publishing on crates.io
> prepare histogram crate for publishing

- histogram/Cargo.toml
- histogram/README.md
Histogram crate was missing a description in its metadata, which prevents publishing to crates.io
> add description to histogram crate metadata

- metriken/Cargo.toml
Adds a description to the metriken crate metadata
> add description for metriken crate

- Cargo.toml
- awaken/Cargo.toml
- awaken/src/lib.rs
Imports the Pelikan waker crate into rustcommon and renames it to `awaken`
> import Pelikan waker crate

- switchboard/Cargo.toml
- switchboard/src/lib.rs
Imports the Pelikan `queues` crate and renames it to `switchboard`.
> import Pelikan queues as switchboard

- heatmap/Cargo.toml
- heatmap/src/heatmap.rs
- heatmap/src/window.rs
- histogram/Cargo.toml
- histogram/src/histogram.rs
Fixes some issues when reading and writing to the heatmap concurrently.
We combine the subtract and clear steps required to zero out a slice in the
heatmap with a combined function in the histogram crate. This allows us to make
use of a swap + fetch_sub and eliminates a potential case where an increment
could happen between the load + fetch_sub and the eventual store of the two step
subtract + clear.
In the heatmap crate, we create one additional slice per heatmap so that we can
always maintain a cleared histogram in the heatmap to begin writing into. We
also move the bulk of the `tick()` logic, which is responsible for moving the
pointers forward and clearing the oldest slice, into a critical block. This
should eliminate a lot of potential concurrency bugs.
> fix: heatmap summary may contain old values

- heatmap/Cargo.toml
- metriken/Cargo.toml
- ratelimit/Cargo.toml
- ringlog/Cargo.toml
- switchboard/Cargo.toml
- waterfall/Cargo.toml
Updates the dependencies on rustcommon crates. This ensures that the fixed version of `heatmap` is used throughout. Additionally, changes all dependencies on rustcommon crates to include a path in addition to a version. This will make changes that effect multiple crates easier in the future.
> chore: update dependencies on rustcommon crates

- waterfall/Cargo.toml
Missed a bump of the version number for `waterfall` in #19
> chore: prepare waterfall crate for release

- heatmap/src/heatmap.rs
I would like to be able to access the buckets of the summary histogram. Using the iterator implementation for `&Heatmap` it is possible to get access to all the other component histograms but not the summary one. This PR just adds a `summary` method to `Heatmap` which returns a reference to the summary histogram.
> feat: Add a summary method to Heatmap to access the summary histogram

- heatmap/src/heatmap.rs
`&Heatmap` implements `IntoIterator` but it does not have an `iter` method. This is somewhat confusing since in most cases where a type `&T` implements `IntoIterator` `T` also has an `iter` method that does the same thing. All this PR does is address this missing method.
> feat: Add `Heatmap::iter` method

- heatmap/src/heatmap.rs
- heatmap/src/window.rs
Previously, the heatmap would only record into the "current" slice. This meant that we could only record past events into the most recent time slice.
This change adds some additional fields to the heatmap to track the represented span of time for the overall heatmap and each time slice. We leave a fast path in-place for when the sample time falls into the span for the current slice. If it does not, we calculate the correct offset into the heatmap and record into that older slice.
By making this change, we can correctly record based on event start time instead of event stop time.
> heatmap: allow recording sample into older slice

- heatmap/Cargo.toml
- metriken/Cargo.toml
Update version numbers and prepare for release heatmap 0.7.3 and metriken 0.1.2
> chore: release heatmap and metriken

- histogram/src/histogram.rs
- histogram/src/lib.rs
Addresses two panic cases within this crate and fixes the
percentiles()` function to return the correct results.
There's a wrapping math operation which occurs when calculating the
upper bound of the highest bucket when the histogram is configured
to cover the entired 64bit range. This is addressed by returning
the histogram's max value if the bucket is the last bucket.
Additionally, as reported in #25 we perform a bounds check after
we index into an array in the `percentiles()` function. This will
reliably cause a panic. However, there are also issues with the
returned results after correcting the panic condition.
Fixes the logic in the `percentiles()` function to both avoid
out of bounds access and return the correct results.
> fix: histogram panics

- histogram/src/histogram.rs
I haven't checked to see if this off-by-one exists in other places. This fixes the bug and adds a test. 
I'm not sure about the use of `NonZeroU64` - maybe that condition should be checked with an assert instead?
> fix a histogram builder off-by-one in Builder::min_resolution

- histogram/src/histogram.rs
- histogram/src/lib.rs
The decrement function currently increments the value. Fix by using
fetch_sub() instead of fetch_add().
> histogram: Fix decrement function

- histogram/src/histogram.rs
- histogram/src/lib.rs
The buckets in a histogram are deterministically generated depending on the m, r, and n parameters representing the values and the granularity being tracked. Exporting these allows for the generation of identical histograms.
> histogram: export histogram resolution parameters

- metriken/Cargo.toml
- metriken/LICENSE-APACHE
- ringlog/Cargo.toml
This is the first PR in a series for updating metriken. All it does is update the authorship info, version, and detach ringlog from metriken so that CI passes.
> Update authorship info for the metriken crate

- metriken/src/dynmetrics.rs
- metriken/src/lib.rs
- metriken/src/null.rs
- metriken/tests/dynmetrics.rs
This is the second PR for implementing #44. It includes the `MetricBuilder` type and the related changes to make existing dynamic metrics work with the metric builder. It is a prerequisite for more invasive changes like adding new fields to `MetricEntry`.
> feat(metriken): Add a new `MetricBuilder` type to make creating dynamic metrics easier

- metriken/Cargo.toml
- metriken/src/dynmetrics.rs
- metriken/src/lib.rs
- metriken/src/metadata.rs
This PR extracts the `Metadata` type from #44. It adds enough that it can be used for dynamic metrics but it is not yet wired up to the `#[metric]` macro.
> feat(metriken): Introduce new `Metadata` type and add it to `MetricEntry`.

- metriken/src/counter.rs
- metriken/src/gauge.rs
- metriken/src/heatmap.rs
- metriken/src/lazy.rs
- metriken/src/lib.rs
- metriken/src/null.rs
As discussed when we were reviewing the changes to metriken. This is somewhat the minimal possible design to work for rezolus and I anticipate it being changed in the future as we try to use it.
> feat(metriken): Add a `Value` type to abstract over different metriken metric types

- metriken/derive/src/metric.rs
- metriken/src/dynmetrics.rs
- metriken/src/formatter.rs
- metriken/src/lib.rs
- metriken/tests/formatter.rs
Wires up the formatter so that we can specify and use custom metric formatters for various exposition formats.
> feat(metriken): wire up the formatter

- ringlog/Cargo.toml
- ringlog/src/lib.rs
Updates ringlog to use the in-tree version of metriken.
> chore(ringlog): update ringlog to use in-tree version of metriken

- ringlog/Cargo.toml
- ringlog/src/lib.rs
Updates ringlog to use the in-tree version of metriken.
> chore(ringlog): use in-tree version of metriken

- heatmap/Cargo.toml
- heatmap/src/lib.rs
- metriken/Cargo.toml
- metriken/src/heatmap.rs
Fix to allow iterating over the heatmap.
> fix(metriken): allow iteration over heatmap

- histogram/Cargo.toml
- histogram/src/bucket.rs
- histogram/src/compact.rs
- histogram/src/histogram.rs
- histogram/src/lib.rs
Add a compact (sparse and columnar) serializable representation of
the histogram for storage and transfer, along with to and fro conversion
functions.
> histogram: add compact serializable representation

- metriken/derive/src/lib.rs
- metriken/src/formatter.rs
1. found a place that is out of sync with the crate name change;
2. fixed a Metriken function that's missing description.
> metriken: documentation comment updates

- clocksource/Cargo.toml
- clocksource/src/precise/duration.rs
Adds some infallible constructors for durations that take lower precision values to avoid possible overflow cases.
Renames a try type constructor to try_from for consistency.
> feat(clocksource): additional duration constructors

- histogram/src/config.rs
Change some of the functions for the `Config` struct to be const. This enables their use in const contexts which will be useful in metriken.
> histogram: make some functions const

- histogram/src/standard.rs
Reorder the tests to prevent unnecessary allocation when the checks fail. Also add unit tests.
> histogram: add unit tests and reorder checks and allocations on add/subtract

- ratelimit/src/lib.rs
Reported in #72 as a panic on overflow in debug mode. Root cause is a race between a thread that has successfully refilled the token bucket and a thread that then steals the newly acquired token.
This can be reliably triggered using the repro code in the original issue with the addition of a sleep in the refill function immediately before the return of `Ok(())`.
What happens before this patch is that thread A refills the bucket successfully, meaning that refill result is `Ok(())` but by the time it loads the available count, there are no more tokens available (due to other threads acquiring tokens in parallel). This means that we do not early return a refill error indicating the duration until next refill, but instead proceed with available as zero.
This fix adds another loop in the token …
> fix(ratelimit): race condition on refill

- histogram/Cargo.toml
- histogram/src/config.rs
- histogram/src/errors.rs
- histogram/src/snapshot.rs
- histogram/src/standard.rs
Allow downsampling of the histogram and snapshot. This trades
space for increased relative error.
> histogram: allow downsampling

- Cargo.toml
Problem
This clippy warning 
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
Solution
Just followed the solution suggested  in the warning 
Result
No clippy warnings.
> Resolved the issue below, as  reported by cargo clippy.

- histogram/src/standard.rs
Skipping empty buckets significantly speeds up downsampling for sparse
histograms. For a histogram with a config of (7, 64) and 100 samples,
this results in around a 5x speedup.
> histogram: skip empty buckets while downsampling

- histogram/Cargo.toml
- histogram/src/standard.rs
Exposes the `Histogram::checked_add` and `wrapping_add` functions publicly.
> feat(histogram): expose histogram add functions

- histogram/Cargo.toml
- histogram/src/config.rs
- histogram/src/errors.rs
- histogram/src/lib.rs
- histogram/src/sparse.rs
- metriken/Cargo.toml
- ringlog/Cargo.toml
Add a sparse representation of the histogram which only stores non-zero
buckets. Optionally add serde bindings to the SparseHistogram so that
it can be serialized as a storage format. The histogram store's bucket
data in a columnar representation, with the indices and the values stored
in individual arrays, as this results in smaller footprint when serialized.
> histogram: add sparse representation

- histogram/Cargo.toml
- histogram/src/sparse.rs
- histogram/src/standard.rs
The existing downsampling interface takes a reduction factor and
downsamples the histogram accordingly. Change this to take the
target grouping power, rather than the factor.
> histogram: change downsampling to take target grouping power

- ratelimit/Cargo.toml
- ratelimit/src/lib.rs
Updates ratelimit to use clocksource 0.7.1
Resolves #89
> update ratelimit to use clocksource 0.7.1

- histogram/Cargo.toml
- histogram/src/config.rs
- histogram/src/sparse.rs
I would like to add a schemars integration to rpcperf-dataspec but since it depends on the histogram crate I need to add support here first.
The details are pretty straightforward:
- I've added a new `schemars` feature to `histogram` - it also enables the `serde-serialize` feature
- I've added a `#[derive(JsonSchema)]` anywhere there was an existing `#[derive(Serialize, Deserialize)]` annotation.
That's it.
I'm not entirely sure how things will work if `schemars` performs a new major version bump but it seems to update fairly slowly so it is unlikely to be a problem for a few years.
> Add schemars integration to histogram

- histogram/Cargo.toml
- histogram/src/config.rs
- histogram/src/sparse.rs
- metriken/Cargo.toml
- metriken/derive/Cargo.toml
- ringlog/Cargo.toml
Renames the serde feature to better match conventions.
> histogram: rename serde feature

- metriken/derive/Cargo.toml
No point in using outdated versions of proc-macro-crate and syn
> Update dependencies for metriken-derive

- metriken/core/Cargo.toml
This also update the metriken dev-dependency to a path dependency only so it is possible to upload it to crates.io
> Add a description to metriken-core

- histogram/src/standard.rs
This test is flaky. I have opened an issue to track it at https://github.com/pelikan-io/rustcommon/issues/100
> Ignore test `histogram::standard::tests::downsample`

- metriken/README.md
- metriken/core/README.md
- metriken/derive/README.md
- metriken/src/lib.rs
Currently none of these crates have a readme on crates.io. That's not great so this PR adds one.
> Add a basic readme to all the metriken crates

- metriken/Cargo.toml
- metriken/src/lib.rs
- metriken/tests/as_any.rs
This copies the same PR from #104 but bases it on the `metriken-v4` branch.
> Fix unbounded recursion in Metric impl for CoreMetric (metriken v0.4.2) 

- metriken/Cargo.toml
- metriken/src/lib.rs
- metriken/tests/as_any.rs
Note: **this is a PR against the metriken-v3 backport branch**
All these infinitely recurse. Unfortunately the recursion was indirect so it was not caught by rustc.
> Fix unbounded recursion in Metric impl for CoreMetric (metriken v0.3.5)

- clocksource/Cargo.toml
- clocksource/src/coarse/duration.rs
- clocksource/src/lib.rs
- clocksource/src/sys/windows.rs
Adds a few additional methods for coarse duration to return other units.
> clocksource: add additional methods for coarse duration

- histogram/Cargo.toml
- histogram/src/snapshot.rs
- histogram/src/sparse.rs
- histogram/src/standard.rs
- metriken/Cargo.toml
- ringlog/Cargo.toml
Expands serde coverage for histogram crate.
Updates metriken to use latest histogram version.
Updates ringlog to use latest metriken version.
> expand serde coverage for histogram crate

- ratelimit/Cargo.toml
- ratelimit/src/lib.rs
Adds a tracking counter for the number of tokens dropped due to bucket overflow.
> ratelimit: add tracking for number of dropped tokens

- histogram/src/atomic.rs
I would like to use `AtomicHistogram` in a metrics-collection/publishing context. In order to avoid additional synchronization primitives, I need the ability to simultaneously produce a new histogram for analysis while draining all stored values from the histogram.
Some of the docs were also out of date, and I fixed those as well.
Add a `drain` method that uses `AtomicU64::swap` to reset buckets to zero as they are consumed. This method is only available on platforms where 64 bit atomics are available and is cfg-gated accordingly.
> Add drain method to AtomicHistogram

- histogram/Cargo.toml
- histogram/src/errors.rs
- histogram/src/sparse.rs
Allow a histogram to be subtracted from another, as long as it
is a proper subset of the other histogram. This is a diff operation
and allows delta histograms to be extracted from free-running ones.
> histogram: add subtract operation for sparse histograms

- histogram/Cargo.toml
- histogram/src/atomic.rs
- histogram/src/sparse.rs
- histogram/src/standard.rs
When the histogram is empty, the percentiles function
currently returns the first bucket for the standard
histogram and panics due to an underflow in the sparse
histogram. Change the signature to return an Optional
value, which is set to None in the empty histogram case
for both standard and sparse histograms.
Also, add a batched percentile lookup for the sparse
histogram to bring the interface in line with the
standard histogram.
> histogram: fix percentiles for empty histograms

- histogram/src/atomic.rs
- histogram/src/config.rs
- histogram/src/standard.rs
We have some size tests in the histogram crate that are sensitive to the platform pointer width. As such, they fail on 32bit systems as reported in #123 
This change restricts these tests to only run on platforms with the expected pointer width.
> run size tests only on 64bit platforms

- ratelimit/src/lib.rs
Useful to check whether the rate limiter has been is use in the recent past, e.g. to drop obsolete per client rate limiters.
p.s.:
`cargo clippy` currently fails for me due to:
```
error: written amount is not handled
--> awaken/src/lib.rs:103:19
|
103 |             match (&self.inner).write(&[1, 0, 0, 0, 0, 0, 0, 0]) {
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: use `Write::write_all` instead, or handle partial writes
note: the result is consumed here, but the amount of I/O bytes remains unhandled
--> awaken/src/lib.rs:104:17
|
104 |                 Ok(_) => Ok(()),
|                 ^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
= note: `#[deny(clippy::unused_io_amount)]` on by …
```
> ratelimit: add method to retrieve the next refill time

- ratelimit/Cargo.toml
- waterfall/Cargo.toml
As reported in #122 we have some broken links. This change updates those links to point to the github repo.
> fix homepage links in cargo manifests

- histogram/Cargo.toml
- ratelimit/Cargo.toml
- waterfall/Cargo.toml
Update version number to prepare for releases for:
* histogram 0.11.1
* ratelimit 0.10.0
* waterfall 0.8.2
> prepare for releases

- histogram/src/standard.rs
Adds `.iter()` to the standard histogram.
> histogram: add `.iter()`

- histogram/Cargo.toml
Prepare histogram crate release 0.11.2
Adds `.iter()` for standard histogram.
> histogram: prepare for release 0.11.2

- histogram/Cargo.toml
- histogram/src/sparse.rs
- histogram/src/standard.rs
Previously, the percentiles functions would report the first bucket as the 0.0th percentile, even if it was empty. We would expect instead that it returns the first bucket with a non-zero count.
This fix wraps the calculation so that low percentiles will always need to find a bucket with at least a count of one.
As a result, percentiles() can now be used to find the proper min, max, and any other percentiles one may need to report out.
Fixes #133
> fix: percentile now properly finds the min bucket
