- heatmap/Cargo.toml
Prepare heatmap crate for publishing on crates.io
> prepare heatmap crate for publishing

- ratelimit/examples/blastoff.rs
- ratelimit/examples/bursty.rs
Fix examples in the ratelimit crate
> fix ratelimit examples

- .github/workflows/cargo.yml
- metrics/Cargo.toml
- ratelimit/Cargo.toml
- ratelimit/examples/blastoff.rs
- ratelimit/examples/bursty.rs
- ratelimit/src/lib.rs
- waterfall/CHANGELOG.md
- waterfall/Cargo.toml
- waterfall/README.md
- waterfall/examples/simulator.rs
- Prepare waterfall crate for publishing to crates.io
- Changes metrics crate to use dependencies from crates.io
- Fixes doctests for ratelimit crate
> fixes and prepare to publish waterfall

- metriken/Cargo.toml
Prepares the metriken crate for publishing to crates.io
> prepare metriken for publishing

- Cargo.toml
Missed adding switchboard crate to workspace manifest in #14
> add switchboard to workspace

- switchboard/Cargo.toml
- switchboard/src/lib.rs
Fix switchboard crate tests to rely on mio directly.
> fix: switchboard tests

- .github/workflows/cargo.yml
This PR updates CI with the same changes as those added to pelikan in https://github.com/pelikan-io/pelikan/pull/61.
> chore: Update CI workflow to make better use of caching

- heatmap/Cargo.toml
Updates version number and prepares heatmap for release 0.7.2
> chore: prepare heatmap for release 0.7.2

- heatmap/Cargo.toml
- histogram/Cargo.toml
- metriken/Cargo.toml
Prepare for release:
heatmap 0.7.4
histogram 0.7.2
metriken 0.1.3
> chore: prepare for release

- metriken/src/dynmetrics.rs
- metriken/src/lib.rs
- ringlog/src/multi.rs
- ringlog/src/nop.rs
- switchboard/src/lib.rs
Addresses all current clippy warnings
> chore: address clippy warnings

- heatmap/src/heatmap.rs
Adds functionality to the heatmap to allow it to be aligned to the top of the second by comparing the monotonic clock and realtime clock during initialization.
> feature: allow the heatmap to be aligned to wall clock

- heatmap/Cargo.toml
- histogram/Cargo.toml
- metriken/Cargo.toml
Updates the version numbers and prepares for release of
* heatmap 0.7.4
* histogram 0.7.3
* metriken 0.1.3
> prepare for release

- metriken/Cargo.toml
- metriken/derive/src/lib.rs
- metriken/src/lib.rs
> feat(metriken): Clean up bits of metriken that are no longer needed or used

- metriken/Cargo.toml
- metriken/src/heatmap.rs
This is the heatmap changes from #43. This is another part of #44. It should be one of the last few changes still needed.
> feat(metriken): Rework the `Heatmap` type

- heatmap/Cargo.toml
- heatmap/src/heatmap.rs
- heatmap/src/lib.rs
- metriken/Cargo.toml
- metriken/src/heatmap.rs
Allows fetching multiple percentiles at once.
> feat(metriken): allow fetching multiple percentiles at once

- ratelimit/Cargo.toml
Update version number and prepare for release
> release(ratelimit): prepare for release 0.7.1

- ringlog/Cargo.toml
Update version number to prepare for release
> ringlog: prepare for release 0.3.0

- metriken/Cargo.toml
- ringlog/Cargo.toml
Increment version numbers to prepare for release
> prepare metriken and ringlog for release

- metriken/Cargo.toml
- metriken/core/Cargo.toml
- metriken/derive/Cargo.toml
This is in preparation for a new release with actual readmes.
> Bump the versions of all metriken crates

- histogram/Cargo.toml
Update version number to prepare for release
> prepare for release histogram 0.10.1

- ringlog/Cargo.toml
> ringlog: update metriken dependency

- ringlog/Cargo.toml
- ringlog/src/lib.rs
- ringlog/src/macros.rs
- ringlog/src/metrics.rs
- ringlog/src/outputs.rs
- ringlog/src/sampling.rs
- ringlog/src/single.rs
Updates ringlog to make metrics optional.
> ringlog: make metrics optional
